/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.sisges.views;

import br.senai.sc.sisges.dao.AgendaDao;
import br.senai.sc.sisges.modelo.Agenda;
import br.senai.sc.sisges.views.CadastroColaborador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadastroAgenda extends javax.swing.JPanel {

    /**
     * Creates new form CadastroAgenda
     */
    public CadastroAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCadastroCliente = new javax.swing.JLabel();
        lbNomTarefa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cpNomTarefa = new javax.swing.JTextField();
        lblDescAgenda = new javax.swing.JLabel();
        cpDesAgenda = new javax.swing.JTextField();
        lblDataInicial = new javax.swing.JLabel();
        cpDataInicial = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();
        lblDataFinal = new javax.swing.JLabel();
        cpDataFinal = new javax.swing.JFormattedTextField();

        labelCadastroCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCadastroCliente.setText(" Cadastrar Agenda");

        lbNomTarefa.setText("Nome tarefa:");

        cpNomTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpNomTarefaActionPerformed(evt);
            }
        });

        lblDescAgenda.setText("Descrição Agenda :");

        lblDataInicial.setText("Data Inicial ");

        try {
            cpDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**/**/****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpDataInicialActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblDataFinal.setText("Data Final ");

        try {
            cpDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**/**/****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpDataFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNomTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpNomTarefa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCadastroCliente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescAgenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpDesAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataFinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomTarefa)
                    .addComponent(cpNomTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicial)
                    .addComponent(cpDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDataFinal)
                    .addComponent(cpDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescAgenda)
                    .addComponent(cpDesAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCadastrar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cpNomTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpNomTarefaActionPerformed

    }//GEN-LAST:event_cpNomTarefaActionPerformed

    private void cpDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpDataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpDataInicialActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Agenda ag = new Agenda();
        
        ag.setDatComAge(cpDataFinal.getText()); //Data de prazo
        ag.setDatCriAge(cpDataInicial.getText());
        ag.setDesAge(cpDesAgenda.getText());
        ag.setTitAge(cpNomTarefa.getText());       

        String DataFinal = cpDataFinal.getText();
        DataFinal = DataFinal.replaceAll("[^0-9]", "");

        String DataInicial = cpDataInicial.getText();
        DataInicial = DataInicial.replaceAll("[^0-9]", "");

      

        

        //Inseri o funcionario no banco de dados
      AgendaDao ageDao = new AgendaDao();
        try {
            ageDao.inserir(ag);
            JOptionPane.showMessageDialog(null, "Funcionário inserido com sucesso !");
        } catch (SQLException ex) {
            Logger.getLogger(CadastroColaborador.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Falha ao inserir Funcionário !");

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cpDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpDataFinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JFormattedTextField cpDataFinal;
    private javax.swing.JFormattedTextField cpDataInicial;
    private javax.swing.JTextField cpDesAgenda;
    private javax.swing.JTextField cpNomTarefa;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCadastroCliente;
    private javax.swing.JLabel lbNomTarefa;
    private javax.swing.JLabel lblDataFinal;
    private javax.swing.JLabel lblDataInicial;
    private javax.swing.JLabel lblDescAgenda;
    // End of variables declaration//GEN-END:variables
}
